#!/bin/sh
.TH PRINTF 3 "2024-03-30" "Version 1.0" "Printf Man Page"

.SH NAME
_printf \- format and print data

.SH SYNOPSIS
.B #include <stdio.h>
.br
.B #include <stdlib.h>
.br
.B #include <stdarg.h>
.br
.B #include <limits.h>
.br
.B #include <unistd.h>
.br
.B #include "main.h"
.br
.B int _printf(const char *format, ...);

.SH DESCRIPTION
The
.B _printf
function formats and prints data to the standard output according to the format string \fIformat\fR.

.PP
The \fIformat\fR string may contain format specifiers that begin with a % character. These are replaced by the subsequent arguments, formatted according to the specifier.

.SH RETURN VALUE
Returns the length of output.

.SH FORMATS
Formats of _printf function:

.TP
.B %c
Prints a character.

.TP
.B %s
Prints a string.

.TP
.B %d, %i
Prints a signed decimal integer.

.SH EXAMPLES
The following code snippet demonstrates the usage of \fI_printf\fR:
.PP
.nf
.B #include <stdio.h>
.br
.B int main() {
.br
.B   _printf("Hello, %s!\n", "world");
.br
.B   return 0;
.br
.B }
.fi

.SH SEE ALSO
.BR printf (3)

.SH REPORTING BUGS
Report bugs to fidanhsynv04@gmail.com

.SH AUTHORS
Fidan Huseynova

.SH COPYRIGHT
Free to use.

.SH DATE
March 2024
